CXX = g++
CXXFLAGS = -std=c++23

%: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

clean:
	rm -f q1_MaxMeanSubArray q2_ReverseVowels q3_ZeroSumSubArrays q4_BackspaceStringCompare q5_ShortestSubstring q6_MissingInteger q7_KAnagrams q8_MergeIntervals q9_DedupArray
