CXX = g++
CXXFLAGS = -std=c++23

%: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<

clean:
	rm -f q1_GraphAlgorithms q2_Heap q3_PriorityQueue q4_NumberOfIslands \
	      q5_FirstKBinaryNumbers q6_RoadNetworks q7_ReverseWords \
	      q8_AlternatingPath q9_MergeKSortedArrays q10_PrerequisiteCourses \
	      q11_VacationDestinations
