//data structure: graph (directed acyclic graph)
//algorithm: topological sort (kahn's / bfs)
//time: O(V+E), space: O(V+E)

#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <queue>
using namespace std;

//uses kahn's algorithm to return courses in valid prerequisite order in O(V+E)
vector<string> prerequisiteCourses(vector<string>& courses,
                                   map<string, vector<string>>& prereqs) {
    map<string, vector<string>> graph;
    map<string, int> indegree;

    for (const auto& c : courses) {
        graph[c];
        indegree[c] = 0;
    }

    for (auto& [course, pres] : prereqs) {
        for (const auto& pre : pres) {
            graph[pre].push_back(course);
            indegree[course]++;
        }
    }

    queue<string> q;
    for (const auto& c : courses) {
        if (indegree[c] == 0) q.push(c);
    }

    vector<string> result;
    while (!q.empty()) {
        string curr = q.front(); q.pop();
        result.push_back(curr);
        for (const auto& next : graph[curr]) {
            if (--indegree[next] == 0) q.push(next);
        }
    }
    return result;
}

//test cases generated by AI
int main() {
    vector<string> courses1 = {"Intro to Programming", "Data Structures",
                                "Advanced Algorithms", "Operating Systems", "Databases"};
    map<string, vector<string>> prereqs1 = {
        {"Data Structures",    {"Intro to Programming"}},
        {"Advanced Algorithms",{"Data Structures"}},
        {"Operating Systems",  {"Advanced Algorithms"}},
        {"Databases",          {"Advanced Algorithms"}}
    };
    auto r1 = prerequisiteCourses(courses1, prereqs1);
    for (const auto& c : r1) cout << c << " -> ";
    cout << endl; // valid topo order ending with OS and Databases

    vector<string> courses2 = {"Intro to Writing", "Contemporary Literature",
                                "Ancient Literature", "Comparative Literature",
                                "Plays & Screenplays"};
    map<string, vector<string>> prereqs2 = {
        {"Contemporary Literature", {"Intro to Writing"}},
        {"Ancient Literature",      {"Intro to Writing"}},
        {"Comparative Literature",  {"Ancient Literature", "Contemporary Literature"}},
        {"Plays & Screenplays",     {"Intro to Writing"}}
    };
    auto r2 = prerequisiteCourses(courses2, prereqs2);
    for (const auto& c : r2) cout << c << " -> ";
    cout << endl; // valid topo order with Intro to Writing first, Comparative Literature last

    return 0;
}

//time spent: 20 minutes
