//data structure: graph (undirected, weighted)
//algorithm: dijkstra's with stopover penalty at intermediate cities
//time: O((V+E) log V), space: O(V+E)

#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <queue>
#include <tuple>
using namespace std;

//uses dijkstra's to count cities reachable within k hours (with +1 stopover at each intermediate city) in O((V+E) log V)
int vacationDestinations(const string& origin, double k,
                         vector<tuple<string, string, double>>& connections) {
    map<string, vector<pair<string, double>>> graph;
    for (auto& [a, b, t] : connections) {
        graph[a].push_back({b, t});
        graph[b].push_back({a, t});
    }

    map<string, double> dist;
    priority_queue<pair<double,string>, vector<pair<double,string>>, greater<>> pq;
    pq.push({0.0, origin});
    dist[origin] = 0.0;

    while (!pq.empty()) {
        auto [d, curr] = pq.top(); pq.pop();
        if (d > dist[curr]) continue; //stale entry

        for (auto& [neighbor, weight] : graph[curr]) {
            double stopover = (curr == origin) ? 0.0 : 1.0; //+1 hour at intermediate cities
            double newDist = d + weight + stopover;
            if (!dist.count(neighbor) || newDist < dist[neighbor]) {
                dist[neighbor] = newDist;
                pq.push({newDist, neighbor});
            }
        }
    }

    int count = 0;
    for (auto& [city, d] : dist) {
        if (city != origin && d <= k) count++;
    }
    return count;
}

//test cases generated by AI
int main() {
    vector<tuple<string,string,double>> connections = {
        {"Boston",       "New York",         4.0},
        {"New York",     "Philadelphia",     2.0},
        {"Boston",       "Newport",          1.5},
        {"Washington DC","Harper's Ferry",   1.0},
        {"Boston",       "Portland",         2.5},
        {"Philadelphia", "Washington DC",    2.5}
    };

    cout << vacationDestinations("New York", 5.0, connections) << endl; // 2
    cout << vacationDestinations("New York", 7.0, connections) << endl; // 4
    cout << vacationDestinations("New York", 8.0, connections) << endl; // 6

    cout << vacationDestinations("New York", 0.0, connections) << endl; // 0

    return 0;
}

//time spent: 25 minutes
