#include <iostream>
#include <map>
#include <set>
#include <vector>
#include <queue>
#include <stack>
using namespace std;

//builds an adjacency set from an edge list
map<int, set<int>> adjacencySet(vector<pair<int, int>> edges) {
    map<int, set<int>> graph;
    for (auto& [a, b] : edges) {
        graph[a].insert(b);
        graph[b]; //ensure destination node exists in map
    }
    return graph;
}

//uses bfs to search for target across all components in O(V+E)
bool bfs(int target, map<int, set<int>> graph) {
    set<int> visited;
    queue<int> q;
    for (auto& [node, _] : graph) {
        if (visited.count(node)) continue;
        visited.insert(node);
        q.push(node);
        while (!q.empty()) {
            int curr = q.front(); q.pop();
            if (curr == target) return true;
            for (int neighbor : graph[curr]) {
                if (!visited.count(neighbor)) {
                    visited.insert(neighbor);
                    q.push(neighbor);
                }
            }
        }
    }
    return false;
}

//helper for dfs
bool dfsHelper(int curr, int target, map<int, set<int>>& graph, set<int>& visited) {
    if (curr == target) return true;
    visited.insert(curr);
    for (int neighbor : graph[curr]) {
        if (!visited.count(neighbor)) {
            if (dfsHelper(neighbor, target, graph, visited)) return true;
        }
    }
    return false;
}

//uses dfs to search for target across all components in O(V+E)
bool dfs(int target, map<int, set<int>> graph) {
    set<int> visited;
    for (auto& [node, _] : graph) {
        if (!visited.count(node)) {
            if (dfsHelper(node, target, graph, visited)) return true;
        }
    }
    return false;
}

//uses kahn's algorithm (bfs) to produce a topological ordering in O(V+E)
vector<int> topologicalSort(map<int, set<int>> graph) {
    map<int, int> indegree;
    for (auto& [node, _] : graph) indegree[node] = 0;
    for (auto& [node, neighbors] : graph) {
        for (int n : neighbors) indegree[n]++;
    }
    queue<int> q;
    for (auto& [node, deg] : indegree) {
        if (deg == 0) q.push(node);
    }
    vector<int> result;
    while (!q.empty()) {
        int curr = q.front(); q.pop();
        result.push_back(curr);
        for (int neighbor : graph[curr]) {
            if (--indegree[neighbor] == 0) q.push(neighbor);
        }
    }
    return result;
}

//helper for dfsTopoSort
void dfsTopoHelper(int curr, map<int, set<int>>& graph, set<int>& visited, stack<int>& stk) {
    visited.insert(curr);
    for (int neighbor : graph[curr]) {
        if (!visited.count(neighbor)) {
            dfsTopoHelper(neighbor, graph, visited, stk);
        }
    }
    stk.push(curr);
}

//uses dfs post-order to produce a topological ordering in O(V+E)
vector<int> topologicalSortDfs(map<int, set<int>> graph) {
    set<int> visited;
    stack<int> stk;
    for (auto& [node, _] : graph) {
        if (!visited.count(node)) {
            dfsTopoHelper(node, graph, visited, stk);
        }
    }
    vector<int> result;
    while (!stk.empty()) {
        result.push_back(stk.top());
        stk.pop();
    }
    return result;
}

//helper to print graph
void printGraph(map<int, set<int>>& g) {
    for (auto& [node, neighbors] : g) {
        cout << node << ": [";
        bool first = true;
        for (int n : neighbors) {
            if (!first) cout << ", ";
            cout << n;
            first = false;
        }
        cout << "]" << endl;
    }
}

//helper to print a vector
void print(const vector<int>& v) {
    cout << "[";
    for (int i = 0; i < (int)v.size(); i++) {
        if (i) cout << ", ";
        cout << v[i];
    }
    cout << "]" << endl;
}

//test cases generated by AI
int main() {
    vector<pair<int,int>> edges = {{1,2},{2,3},{1,3},{3,2},{2,0}};
    auto g = adjacencySet(edges);
    printGraph(g); // 0:[], 1:[2,3], 2:[0,3], 3:[2]

    cout << bfs(0, g) << endl;  // 1 (found)
    cout << bfs(5, g) << endl;  // 0 (not found)
    cout << dfs(3, g) << endl;  // 1 (found)
    cout << dfs(5, g) << endl;  // 0 (not found)

    vector<pair<int,int>> dagEdges = {{0,1},{0,2},{1,3},{2,3},{3,4}};
    auto dag = adjacencySet(dagEdges);
    cout << "Kahn's topo: "; print(topologicalSort(dag));      // [0,1,2,3,4] or valid order
    cout << "DFS topo:    "; print(topologicalSortDfs(dag));   // [0,2,1,3,4] or valid order

    return 0;
}

//time spent: 35 minutes
