#include <iostream>
#include <vector>
using namespace std;

//min heap implemented with a dynamic array using bubble up/down in O(log n) per operation
class Heap {
private:
    vector<int> arr;

    int parent(int i) { return (i - 1) / 2; }
    int left(int i)   { return 2 * i + 1; }
    int right(int i)  { return 2 * i + 2; }

    void bubbleUp(int i) {
        while (i > 0 && arr[parent(i)] > arr[i]) {
            swap(arr[parent(i)], arr[i]);
            i = parent(i);
        }
    }

    void bubbleDown(int i) {
        int n = arr.size();
        while (true) {
            int smallest = i;
            if (left(i)  < n && arr[left(i)]  < arr[smallest]) smallest = left(i);
            if (right(i) < n && arr[right(i)] < arr[smallest]) smallest = right(i);
            if (smallest == i) break;
            swap(arr[i], arr[smallest]);
            i = smallest;
        }
    }

public:
    int top() { return arr[0]; }

    void insert(int x) {
        arr.push_back(x);
        bubbleUp(arr.size() - 1);
    }

    void remove() {
        arr[0] = arr.back();
        arr.pop_back();
        if (!arr.empty()) bubbleDown(0);
    }

    bool empty() { return arr.empty(); }
    int size()   { return arr.size(); }
};

//test cases generated by AI
int main() {
    Heap h;
    h.insert(5);
    h.insert(3);
    h.insert(8);
    h.insert(1);
    h.insert(6);

    while (!h.empty()) {
        cout << h.top() << " ";
        h.remove();
    }
    cout << endl;

    Heap h2;
    h2.insert(10);
    h2.insert(2);
    h2.insert(7);
    cout << h2.top() << endl; // 2
    h2.remove();
    cout << h2.top() << endl; // 7

    return 0;
}

//time spent: 20 minutes
