#include <iostream>
#include <vector>
#include <string>
using namespace std;

//max heap keyed on priority; higher weight = higher priority, O(log n) per insert/remove
class PriorityQueue {
private:
    vector<pair<string, int>> arr;

    int parent(int i) { return (i - 1) / 2; }
    int left(int i)   { return 2 * i + 1; }
    int right(int i)  { return 2 * i + 2; }

    void bubbleUp(int i) {
        while (i > 0 && arr[parent(i)].second < arr[i].second) {
            swap(arr[parent(i)], arr[i]);
            i = parent(i);
        }
    }

    void bubbleDown(int i) {
        int n = arr.size();
        while (true) {
            int largest = i;
            if (left(i)  < n && arr[left(i)].second  > arr[largest].second) largest = left(i);
            if (right(i) < n && arr[right(i)].second > arr[largest].second) largest = right(i);
            if (largest == i) break;
            swap(arr[i], arr[largest]);
            i = largest;
        }
    }

public:
    string top() { return arr[0].first; }

    void insert(string x, int weight) {
        arr.push_back({x, weight});
        bubbleUp(arr.size() - 1);
    }

    void remove() {
        arr[0] = arr.back();
        arr.pop_back();
        if (!arr.empty()) bubbleDown(0);
    }

    bool empty() { return arr.empty(); }
};

//test cases generated by AI
int main() {
    PriorityQueue pq;
    pq.insert("low", 1);
    pq.insert("high", 10);
    pq.insert("medium", 5);
    pq.insert("critical", 20);

    while (!pq.empty()) {
        cout << pq.top() << endl; // critical, high, medium, low
        pq.remove();
    }

    PriorityQueue pq2;
    pq2.insert("task A", 3);
    pq2.insert("task B", 7);
    pq2.insert("task C", 7);
    cout << pq2.top() << endl; // task B or task C
    pq2.remove();
    cout << pq2.top() << endl; // task C or task B

    return 0;
}

//time spent: 10 minutes
