//data structure: graph (implicit grid)
//algorithm: dfs
//time: O(m*n), space: O(m*n)

#include <iostream>
#include <vector>
using namespace std;

//helper: sinks connected land cells via dfs
void dfs(vector<vector<int>>& grid, int r, int c) {
    int rows = grid.size(), cols = grid[0].size();
    if (r < 0 || r >= rows || c < 0 || c >= cols || grid[r][c] == 0) return;
    grid[r][c] = 0;
    dfs(grid, r + 1, c);
    dfs(grid, r - 1, c);
    dfs(grid, r, c + 1);
    dfs(grid, r, c - 1);
}

//counts islands by dfs-sinking each unvisited land cell in O(m*n)
int numberOfIslands(vector<vector<int>> grid) {
    int count = 0;
    for (int r = 0; r < (int)grid.size(); r++) {
        for (int c = 0; c < (int)grid[0].size(); c++) {
            if (grid[r][c] == 1) {
                count++;
                dfs(grid, r, c);
            }
        }
    }
    return count;
}

//test cases generated by AI
int main() {
    vector<vector<int>> g1 = {
        {1, 0, 1, 1, 1},
        {1, 1, 0, 1, 1},
        {0, 1, 0, 0, 0},
        {0, 0, 0, 1, 0},
        {0, 0, 0, 0, 0}
    };
    cout << numberOfIslands(g1) << endl; // 3

    vector<vector<int>> g2 = {
        {1, 0, 0},
        {0, 0, 0}
    };
    cout << numberOfIslands(g2) << endl; // 1

    vector<vector<int>> g3 = {
        {1, 1, 1},
        {1, 1, 1}
    };
    cout << numberOfIslands(g3) << endl; // 1

    vector<vector<int>> g4 = {
        {1, 0, 1},
        {0, 0, 0},
        {1, 0, 1}
    };
    cout << numberOfIslands(g4) << endl; // 4

    return 0;
}

//time spent: 15 minutes
