//data structure: queue
//time: O(k * log k), space: O(k)

#include <iostream>
#include <vector>
#include <string>
#include <queue>
using namespace std;

//uses a queue to generate the first k binary numbers in order in O(k log k)
vector<string> firstKBinaryNumbers(int k) {
    vector<string> result;
    if (k == 0) return result;
    result.push_back("0");
    queue<string> q;
    q.push("1");
    while ((int)result.size() < k) {
        string curr = q.front(); q.pop();
        result.push_back(curr);
        q.push(curr + "0");
        q.push(curr + "1");
    }
    return result;
}

//test cases generated by AI
int main() {
    auto r1 = firstKBinaryNumbers(5);
    for (const auto& s : r1) cout << s << " ";
    cout << endl; // 0 1 10 11 100

    auto r2 = firstKBinaryNumbers(10);
    for (const auto& s : r2) cout << s << " ";
    cout << endl; // 0 1 10 11 100 101 110 111 1000 1001

    auto r3 = firstKBinaryNumbers(1);
    for (const auto& s : r3) cout << s << " ";
    cout << endl; // 0

    auto r4 = firstKBinaryNumbers(0);
    cout << r4.size() << endl; // 0

    return 0;
}

//time spent: 10 minutes
