//data structure: graph (undirected, adjacency list)
//algorithm: bfs (connected components)
//time: O(V+E), space: O(V+E)

#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <set>
#include <queue>
using namespace std;

//counts connected components with more than one town using bfs in O(V+E)
int roadNetworks(vector<string>& towns, vector<pair<string, string>>& roads) {
    map<string, vector<string>> graph;
    for (const auto& town : towns) graph[town];
    for (const auto& [a, b] : roads) {
        graph[a].push_back(b);
        graph[b].push_back(a);
    }

    set<string> visited;
    int networks = 0;
    for (const auto& town : towns) {
        if (visited.count(town)) continue;
        queue<string> q;
        q.push(town);
        visited.insert(town);
        int componentSize = 0;
        while (!q.empty()) {
            string curr = q.front(); q.pop();
            componentSize++;
            for (const auto& neighbor : graph[curr]) {
                if (!visited.count(neighbor)) {
                    visited.insert(neighbor);
                    q.push(neighbor);
                }
            }
        }
        if (componentSize > 1) networks++; //isolated towns are not road networks
    }
    return networks;
}

//test cases generated by AI
int main() {
    vector<string> towns1 = {"Skagway", "Juneau", "Gustavus", "Homer", "Port Alsworth",
                              "Glacier Bay", "Fairbanks", "McCarthy", "Copper Center",
                              "Healy", "Anchorage"};
    vector<pair<string,string>> roads1 = {
        {"Anchorage", "Homer"}, {"Glacier Bay", "Gustavus"},
        {"Copper Center", "McCarthy"}, {"Anchorage", "Copper Center"},
        {"Copper Center", "Fairbanks"}, {"Healy", "Fairbanks"},
        {"Healy", "Anchorage"}
    };
    cout << roadNetworks(towns1, roads1) << endl; // 2

    vector<string> towns2 = {"Kona", "Hilo", "Volcano", "Lahaina", "Hana", "Haiku",
                              "Kahului", "Princeville", "Lihue", "Waimea"};
    vector<pair<string,string>> roads2 = {
        {"Kona", "Volcano"}, {"Volcano", "Hilo"}, {"Lahaina", "Hana"},
        {"Kahului", "Haiku"}, {"Hana", "Haiku"}, {"Kahului", "Lahaina"},
        {"Princeville", "Lihue"}, {"Lihue", "Waimea"}
    };
    cout << roadNetworks(towns2, roads2) << endl; // 3

    vector<string> towns3 = {"A", "B", "C"};
    vector<pair<string,string>> roads3 = {};
    cout << roadNetworks(towns3, roads3) << endl; // 0

    vector<string> towns4 = {"X", "Y", "Z"};
    vector<pair<string,string>> roads4 = {{"X","Y"}, {"Y","Z"}};
    cout << roadNetworks(towns4, roads4) << endl; // 1

    return 0;
}

//time spent: 20 minutes
