//data structure: stack
//time: O(n), space: O(n)

#include <iostream>
#include <string>
#include <stack>
#include <sstream>
using namespace std;

//uses a stack to reverse word order in a sentence in O(n)
string reverseWords(const string& s) {
    stack<string> stk;
    istringstream ss(s);
    string word;
    while (ss >> word) stk.push(word);

    string result;
    while (!stk.empty()) {
        result += stk.top();
        stk.pop();
        if (!stk.empty()) result += " ";
    }
    return result;
}

//test cases generated by AI
int main() {
    cout << reverseWords("Uber Career Prep") << endl;            // Prep Career Uber
    cout << reverseWords("Emma lives in Brooklyn, New York.") << endl; // York. New Brooklyn, in lives Emma
    cout << reverseWords("hello") << endl;                       // hello
    cout << reverseWords("a b c d") << endl;                     // d c b a

    return 0;
}

//time spent: 8 minutes
