//data structure: graph (directed, colored edges)
//algorithm: bfs with state (node, last color used)
//time: O(V+E), space: O(V+E)

#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <set>
#include <queue>
#include <tuple>
using namespace std;

//uses bfs to find shortest alternating-color path between two nodes in O(V+E)
int alternatingPath(const string& origin, const string& destination,
                    vector<tuple<string, string, string>>& edges) {
    map<string, vector<pair<string, string>>> graph;
    for (auto& [a, b, color] : edges) {
        graph[a].push_back({b, color});
    }

    if (origin == destination) return 0;

    set<pair<string, string>> visited;
    queue<tuple<string, string, int>> q; //(node, last_color, distance)
    q.push({origin, "none", 0});
    visited.insert({origin, "none"});

    while (!q.empty()) {
        auto [curr, lastColor, dist] = q.front(); q.pop();

        for (auto& [neighbor, color] : graph[curr]) {
            if (color == lastColor) continue; //must alternate
            auto state = make_pair(neighbor, color);
            if (!visited.count(state)) {
                if (neighbor == destination) return dist + 1;
                visited.insert(state);
                q.push({neighbor, color, dist + 1});
            }
        }
    }
    return -1;
}

//test cases generated by AI
int main() {
    vector<tuple<string,string,string>> edges = {
        {"A","B","blue"}, {"A","C","red"},  {"B","D","blue"},
        {"B","E","blue"}, {"C","B","red"},  {"D","C","blue"},
        {"A","D","red"},  {"D","E","red"},  {"E","C","red"}
    };

    cout << alternatingPath("A", "E", edges) << endl; // 4
    cout << alternatingPath("E", "D", edges) << endl; // -1
    cout << alternatingPath("A", "A", edges) << endl; // 0
    cout << alternatingPath("A", "C", edges) << endl; // 1 (A->C red)

    return 0;
}

//time spent: 30 minutes
