//data structure: priority queue (min heap)
//time: O(N log k) where N = total elements, k = number of arrays
//space: O(k) for the heap + O(N) for the result

#include <iostream>
#include <vector>
#include <queue>
#include <tuple>
using namespace std;

//uses a min heap to merge k sorted arrays in O(N log k)
vector<int> mergeKSortedArrays(vector<vector<int>>& arrays) {
    priority_queue<tuple<int,int,int>, vector<tuple<int,int,int>>, greater<>> pq;

    for (int i = 0; i < (int)arrays.size(); i++) {
        if (!arrays[i].empty()) {
            pq.push({arrays[i][0], i, 0});
        }
    }

    vector<int> result;
    while (!pq.empty()) {
        auto [val, arrIdx, elemIdx] = pq.top(); pq.pop();
        result.push_back(val);
        if (elemIdx + 1 < (int)arrays[arrIdx].size()) {
            pq.push({arrays[arrIdx][elemIdx + 1], arrIdx, elemIdx + 1});
        }
    }
    return result;
}

//helper to print a vector
void print(const vector<int>& v) {
    cout << "[";
    for (int i = 0; i < (int)v.size(); i++) {
        if (i) cout << ", ";
        cout << v[i];
    }
    cout << "]" << endl;
}

//test cases generated by AI
int main() {
    vector<vector<int>> a1 = {{1,2,3,4,5}, {1,3,5,7,9}};
    print(mergeKSortedArrays(a1)); // [1,1,2,3,3,4,5,5,7,9]

    vector<vector<int>> a2 = {{1,4,7,9}, {2,6,7,10,11,13,15}, {3,8,12,13,16}};
    print(mergeKSortedArrays(a2)); // [1,2,3,4,6,7,7,8,9,10,11,12,13,13,15,16]

    vector<vector<int>> a3 = {{5}};
    print(mergeKSortedArrays(a3)); // [5]

    vector<vector<int>> a4 = {{}, {1,2}, {}};
    print(mergeKSortedArrays(a4)); // [1,2]

    return 0;
}

//time spent: 15 minutes
